// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAonXuPDyA7eF1Up7S4MYSYe7wwUM-FRtE",
    authDomain: "greenstem-mobile-7de26.firebaseapp.com",
    projectId: "greenstem-mobile-7de26",
    storageBucket: "greenstem-mobile-7de26.firebasestorage.app",
    messagingSenderId: "674248714402",
    appId: "1:674248714402:web:9c18890ea03678f0338ffb"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6svjGzMgJAR3VhQZMETE8onB6DC0Gpw8',
    appId: '1:674248714402:android:debd10ceba0e15ce338ffb',
    messagingSenderId: '674248714402',
    projectId: 'greenstem-mobile-7de26',
    storageBucket: 'greenstem-mobile-7de26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyD6svjGzMgJAR3VhQZMETE8onB6DC0Gpw8",
    appId: "1:674248714402:ios:1010101010101010101010",
    messagingSenderId: "674248714402",
    projectId: "greenstem-mobile-7de26",
    storageBucket: "greenstem-mobile-7de26.firebasestorage.app",
    iosBundleId: "com.example.greenstemAdmin",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyD6svjGzMgJAR3VhQZMETE8onB6DC0Gpw8",
    appId: "1:674248714402:ios:1010101010101010101010",
    messagingSenderId: "674248714402",
    projectId: "greenstem-mobile-7de26",
    storageBucket: "greenstem-mobile-7de26.firebasestorage.app",
    iosBundleId: "com.example.greenstemAdmin",
  );
}

/*
INSTRUCTIONS FOR EXISTING FIREBASE PROJECT:
1. Go to Firebase Console: https://console.firebase.google.com/
2. Select your existing "greenstem-mobile" project
3. Add apps for each platform (Android, iOS, Web)
4. Copy the configuration values from each app
5. Replace the placeholder values in this file with actual values

Alternative: Install Firebase CLI and run:
1. npm install -g firebase-tools
2. firebase login
3. dart pub global run flutterfire_cli:flutterfire configure --project=greenstem-mobile

This will connect your admin app to the same Firebase database as your mobile app.
*/
